---
title: "Logbook Typo Challenge data analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
```

```{r}
######################################################
### read contributions ###
######################################################

date_of_contributions <- "Final"

dat <- readRDS(paste0("./contributions/", date_of_contributions, "/contributions.rds"))

n_entries_per_contribution <- vapply(dat, function(x) nrow(x$data), integer(1))
tmp <- do.call("rbind", lapply(dat, "[[", "data"))
ret <- cbind(id = rep(names(dat), n_entries_per_contribution), tmp, stringsAsFactors = FALSE)
rownames(ret) <- NULL

######################################################
### source functions ###
######################################################
source("R/functions.R")
```

```{r}
######################################################
### Characteristics of contributions ###
######################################################

### number of contributions ###
id_contributions <- names(dat)
n_contributions <- length(id_contributions)

### Number of entries by contribution ### 
hist(table(ret$id), breaks = seq(0, 460, 10), col = "grey", 
     main = "", xlab = "Number of entry by contribution")

```

The dataset collected during the TypoChallenge contains `r nrow(ret)` entries from `r n_contributions` individual contributions. Each contribution includes an average of `r mean(table(ret$id))` entries (median=`r median(table(ret$id))`, sd=`r sd(table(ret$id))`, range=`r range(table(ret$id))`).

```{r}
######################################################
### Characteristics of errors ###
######################################################

### frequency of error (across all contributions) ###
freq_error <- table(ret$correct)['FALSE'] / sum(table(ret$correct))

### frequency of error (per contribution) ###
freq_error_per_contribution <- 
  sapply(id_contributions, compute_freq_error_per_contribution)

par(mfrow=c(1, 2))
hist(freq_error_per_contribution, breaks = seq(0, 1, 0.05), col = "grey", 
     main = "", xlab = "Frequency of error by contribution")
plot(n_entries_per_contribution, freq_error_per_contribution,
     col = scales::alpha("black", 0.5),
     xlab = "Number of entries", ylab = "Frequency of error")

xx <- seq(from=0, to=450, length.out = 1000)
for(i in 1:10)
  lines(xx,i/xx,col=gray(.8))

### looking at the errors made ###
erroneous_ret <- ret[!ret$correct,]

head(erroneous_ret, 20)
```

```{r}
data_modified <- dplyr::filter(ret, elapsed < 50) %>% mutate(perc_error=100*(1-as.numeric(correct)))

p <- ggplot(data_modified, aes(x=elapsed, y=perc_error)) + geom_point(size=2, alpha=0.4) +
stat_smooth(method="loess", colour="blue", size=1.5) + facet_wrap(vars(date_format)) +
  theme_bw() + xlab("Time taken to type (sec)") + ylab("Frequency of error (%)") + ylim(0,105)
p
ggsave("Freq_error.png")

```

```{r}
######################################################
### Characteristics of participants ###
######################################################

countries_from <- unlist(sapply(1:length(dat), function(e) dat[[e]]$survey$country_from))
table(countries_from)

countries_residence <- unlist(sapply(1:length(dat), function(e) dat[[e]]$survey$country_residence))
table(countries_residence)

######################################################
### Plot a map of the origin of contributors ###
######################################################

library("rworldmap")

par(mfrow=c(1, 1))

count_countries <- table(countries_from)
count_countries <- count_countries[-1]

origin_map_df <- data.frame(country = names(count_countries), freq = as.integer(count_countries), stringsAsFactors = F)

origin_map_df$country[which(origin_map_df$country=="Czech Rep.")] <- "Czech republic"
origin_map_df$country[which(origin_map_df$country=="Dominican Rep.")] <- "Dominican republic"

origin_Map <- joinCountryData2Map(origin_map_df, joinCode = "NAME", verbose = TRUE,
                              nameJoinColumn = "country")

mapCountryData(origin_Map, nameColumnToPlot="freq", xlim= c(-160,180), ylim = c(-0,70) , catMethod = "pretty",
               missingCountryCol = gray(.6), oceanCol="#f0f0ffff", addLegend="T",mapTitle = "Typo Challenge contributors")
```

```{r}
erroneous_ret <- ret[!ret$correct,]

date1_char <- erroneous_ret$date # true date
date2_char <- erroneous_ret$user # date entered by user

erroneous_ret <- data.frame(erroneous_ret, detection = NA)

levels(erroneous_ret$detection) <- c("D|M|Y","empty","FullSpell","OneSep","NoSep")

# regular expression to track day sep1 month sep2 year pattern
# ?grep ?regex
re <- "^'?([0-9]+)([[:punct:]]+)([0-9]+)([[:punct:]]+)([0-9]+)[[:punct:]]*$"
recognised_by_regex <- grepl(re, date2_char)
erroneous_ret$detection[recognised_by_regex] <- "D|M|Y"

# empty entries
empty_entries <- date2_char == ""
erroneous_ret$detection[empty_entries] <- "empty"

# fully spelt out date (with space or punctuation to separate dates)
re2 <- "^'?([0-9]+)([[:space:][:punct:]]+)([[:alpha:]]+)([[:space:][:punct:]]+)([0-9]+)[[:punct:]]*$"
full_spell_out_entries <- grepl(re2, date2_char)
date2_char[full_spell_out_entries]
erroneous_ret$detection[full_spell_out_entries] <- "FullSpell"

# missing one field (only one separator)
re3 <- "^'?([0-9]+)([[:punct:]]+)([0-9]+)[[:punct:]]*$"
missing_one_numeric_field <- grepl(re3, date2_char)
erroneous_ret$detection[missing_one_numeric_field] <- "OneSep"

# missing two fields (no separator)
re4 <- "^'?([0-9]+)[[:punct:]]*$"
missing_two_numeric_fields <- grepl(re4, date2_char)
erroneous_ret$detection[missing_two_numeric_fields] <- "NoSep"

### what are we currently not capturing?  
captured <- recognised_by_regex | empty_entries | full_spell_out_entries | missing_one_numeric_field | missing_two_numeric_fields
date2_char[!captured] 
date1_char[!captured] 
prop.table(table(captured)) # <1% of errors not captured by current algorithm --> can look at these manually really!
```
```{r}
library(ggwaffle)

erroneous_ret$detection <- as.character(erroneous_ret$detection)
waffle_data <- waffle_iron(erroneous_ret, aes_d(group = detection), rows=30)

ggplot(waffle_data, aes(x, y, fill = group)) + 
  geom_waffle() + 
  coord_equal() +
  scale_fill_waffle() + 
  theme_waffle()

```



